### ISSUE TITLE
torch installation failed

### ISSUE THREAD

**Issue by Itz-Hyperz** [calebrwalk5/FidiGUI#4]
got this error, please guide me to fix ❤️ 

![error picture](https://cdn.hyperz.net/u/main/qvcTouF.png)

**Comment by Itz-Hyperz** [comment]
Python version: `3.11.1`

![version picture](https://cdn.hyperz.net/u/main/NMjDIjs.png)

**Comment by calebrwalk5** [comment]
@Itz-Hyperz try downloading the latest update of python

**Comment by Itz-Hyperz** [comment]
I'm on the latest version... `3.11.1`

**Comment by Itz-Hyperz** [comment]
Update: Works fine on `3.10.8`, just not `3.11` or later

**Comment by calebrwalk5** [comment]
> Update: Works fine on `3.10.8`, just not `3.11` or later

okay, i will specify this in the readme
