### ISSUE TITLE
Lack of OS detection in `main.py`

### ISSUE THREAD

**Issue by calebrwalk5** [calebrwalk5/FidiGUI#8]
Lines `16` and `19` of `main.py` are Windows-only system calls

**Comment by Itz-Hyperz** [comment]
I vote you write this off as a wontfix label. The only people who will use it anyways are those on windows.

**Comment by calebrwalk5** [comment]
> I vote you write this off as a wontfix label. The only people who will use it anyways are those on windows.

fair enough
